### ISSUE TITLE
?tickets here

### ISSUE THREAD

**Issue by TheSoulrester** [LiBa001/Support-Manager#1]
Hi

Gibt es auch deutschen Support? Ich schreibe einfach mal auf Deutsch:

der Befehl "?tickets here´" bringt aktuell nichts, er gibt mir nur eine weitere Möglichkeit aus mit "?tickets help" welche jedoch keine komplette Übersicht aller offenen bzw. geschlossenen Tickets ausgibt.

Wird es zukünftig derartiges geben?

**Comment by LiBa001** [comment]
@TheSoulrester Habs tatsächlich auch gerade bemerkt. Ich schätze es liegt daran, dass ich vor kurzem den Befehl "tickets all" auf Grund von hoher Latenz entfernen musste. Anscheinend hab ich dabei versehentlich auch den Befehl "tickets here" irgendwie deaktiviert :/

**Comment by LiBa001** [comment]
Okay, müsste jetzt gefixt sein. Der Befehl gibt eine Übersicht über die aktuellen **offenen** Tickets des Servers.
