### ISSUE TITLE
?addinfo ZAHL auch für Supporter

### ISSUE THREAD

**Issue by TheSoulrester** [LiBa001/Support-Manager#2]
Ich wäre dafür, dass auch die Moderatoren/Supporter Informationen zum Ticket hinzufügen können, sodass weiterführende Fragen oder Informationen dem Ticket beigefügt werden können

**Comment by LiBa001** [comment]
Joa, gute Idee muss mal schauen, wann ich dazu komme. Dann müsste ja auch irgendwie gespeichert und angezeigt werden, wer die Information hinzugefügt hat.
