### ISSUE TITLE
self hosting

### ISSUE THREAD

**Issue by codc3** [LiBa001/Support-Manager#3]
how can i host it on my vps linux?

**Comment by LiBa001** [comment]
Sorry, self-hosting isn't wanted, but I'd be interested in why you don't wanna use the official hosted bot?

**Comment by codc3** [comment]
In fact it was to end of study! @LiBa001 


Do you work with private development?
I'm need a bot for my server and wanted to pay a program to do it

**Comment by LiBa001** [comment]
@pedroricardo 

> Do you work with private development?

I'm not exactly sure what you mean. I actually program _for fun_ and I'm not a member of a company.

> I'm need a bot for my server and wanted to pay a program to do it

I would do contract labor, if the the project is fun for me. Just contact me on Discord (_LiBa01#8817_).

**Comment by ghost** [comment]
Heroku.com
